config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'listings#index'
  get '/profile', to: 'profile#index'
  
  resources :listings, :profiles, :farmers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/farmer.rb
class Farmer < ApplicationRecord
    has_many :listings
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :farmer
  belongs_to :produce
  has_many :produces, through: :produce_listings
end

app/models/produce.rb
class Produce < ApplicationRecord
  belongs_to :produce_family
  has_many :listings, through: :produce_listings
end

app/models/produce_family.rb
class ProduceFamily < ApplicationRecord
    has_many :produces, dependent: :destroy
end

app/models/produce_listing.rb
class ProduceListing < ApplicationRecord
  belongs_to :listing
  belongs_to :produce
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
  before_action :set_user, only: [:update, :show, :destroy, :edit]

  def index
    @id = current_user.id
    @farmer = Farmer.all
    
  end

  def show
    @profile = current_user.email
  end

  def update
    
  end

  def edit
    @farmer = Farmer.new
  end

  def delete; end

  def create
    @info = farmer_params
    Farmer.new(first_name: @info['first_name'], last_name: @info['last_name'],
               farm_name: @info['farm_name'], user_id: current_user.id)

    
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def farmer_params
    params.require(:farmer).permit(:first_name, :last_name, :farm_name, current_user.id)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

    ## Authenticate user before any action
    #before_action :authenticate_user!

    def index
        @produce = Produce.all

    end

    def new
        @listing = Listing.new
        @produce = Produce.order(:name)
    end

    def update

    end

    def delete

    end

    def edit

    end

    def show

    end

    def create
        render action: 'index'

    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    before_action :set_user, only: [:update, :show, :destroy, :edit]

    def index
        @id = current_user.id
    end

    def show
        @profile = current_user.email
    end

    def update
        
    end

    def edit
        @farmer = Farmer.new
    end

    def delete

    end


    private

    def set_user
        @user = User.find(params[:id])
    end

    def farmer_params
        params.require(:farmer).permit(:first_name, :last_name, :farm_name, current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/farmers/_form.html.erb
<%= form_with model: @farmer, local: true do |f| %>
    <p>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
    </p>
    <p>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
    </p>
    <p>
        <%= f.label :farm_name %>
        <%= f.text_field :farm_name %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/farmers/create.html.erb
<p><%= @info.each do |i| %></p>
    <p><%= i %></p>
<% end %>

app/views/farmers/edit.html.erb
<%= render 'form' %>

app/views/farmers/index.html.erb
<span><%= link_to 'Update Profile', edit_farmer_path(@id) %></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FarmersMarketplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header><h1>Farmers Marketplace</h1>
      <nav>
        <button>Home</button>
        <button>Profile</button>
        <span>
        <% if user_signed_in? %>
          <%= current_user.email %>
          |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Login", user_session_path%>
          |
          <%= link_to "Sign-Up", new_user_registration_path %>
        <% end %>
        </span>
      </nav>
    </header>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for @listing, local: true do |f| %>
    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %>
        <%= f.text_area :description, size: '40x10' %>
    </p>
    <p>
        <%= f.label :produce %>
        <%= f.collection_select :produce_id, @produce, :id, :name %>
    </p>
    <p>
        <%= f.label :qty %>
        <%= f.text_field :qty, as: :integer %>
    </p>
    <p>
        <%= f.label :price %>
        <%= f.text_field :price, as: :decimal, hint: 'Must be a number' %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/listings/index.html.erb
<span><%= link_to 'Create Listing', new_listing_path %></span>

app/views/listings/new.html.erb
<h1>Hello</h1>

<%= render 'form' %>

app/views/profiles/_form.html.erb
<%= form_with model: @farmer, local: true do |f| %>
    <p>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
    </p>
    <p>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
    </p>
    <p>
        <%= f.label :farm_name %>
        <%= f.text_field :farm_name %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/index.html.erb
<span><%= link_to 'Update Profile', edit_profile_path(@id) %></span>